language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
before_install:
  - sudo apt-get update && sudo apt-get install -y libeigen3-dev
script: ./waf configure && ./waf build_debug && ./build/debug/saucats-unitest
