language: cpp
os:
  - linux
sudo: required
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
install:
  - scripts/travis-install-cmake.sh && export PATH=$(pwd)/cmake/bin:$PATH
  - scripts/travis-install-eigen3.sh
script:
  - ./waf configure && ./waf build_debug
  - ./build/debug/saucats-unitest
