language: cpp
sudo: required
compiler:
  - clang
os:
  - linux
before_install:
  - sudo apt-get update && sudo apt-get install -y libeigen3-dev
script: waf && waf build_debug && ./build/debug/saucats-unitest
