language: cpp
os:
  - linux
sudo: required
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - sudo apt-get update && sudo apt-get install -y libeigen3-dev
install:
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
  - ./waf configure && ./waf build_debug
  - ./build/debug/saucats-unitest
