#! /usr/bin/env python

# the following two variables are used by the target "waf dist"
VERSION = '1.0.0'
APPNAME = 'saucats-examples'

# these variables are mandatory ('/' are converted automatically)
top, out = '.', 'build'



def options(context):
	context.load('compiler_cxx')



def configure(context):
	context.load('compiler_cxx')
	context.env.CXXFLAGS = ['-std=c++14', '-Wall', '-Wextra', '-O3', '-g', '-frounding-math']
	context.check_cfg(package = 'eigen3', uselib_store = 'eigen', args = ['eigen3 >= 3.3', '--cflags'])
	context.check_cfg(package = 'fftw3', uselib_store = 'fftw', args = '--cflags --libs')
	context.check_cfg(package = 'libpng', atleast_version='1.2.0',  uselib_store = 'png', args = '--cflags --libs')
	context.check_cfg(package = 'saucats', uselib_store = 'saucats', args = '--cflags')



def build(context):
	context(
		name            = 'stlparser',
		includes        = 'stlparser/include',
		export_includes = 'stlparser/include'
	)

	context.program(
		target = 'saucats-custom-shader-2d',
		source = context.path.ant_glob('custom-shader-2d/*.cpp'),
		lib    = ['m'],
		use    = ['saucats', 'fftw', 'png', 'eigen']
	)

	context.program(
		target = 'saucats-polygon-dist-field-render',
		source = context.path.ant_glob('polygon-dist-field-render/*.cpp'),
		lib    = ['m'],
		use    = ['saucats', 'fftw', 'png', 'eigen']
	)

	context.program(
		target = 'saucats-torus-render',
		source = context.path.ant_glob('torus-render/*.cpp'),
		lib    = ['m'],
		use    = ['saucats', 'fftw', 'png', 'eigen']
	)

	context.program(
		target = 'saucats-trimesh',
		source = context.path.ant_glob('trimesh/*.cpp'),
		lib    = ['m'],
		use    = ['stlparser', 'saucats', 'fftw', 'png', 'eigen']
	)

	context.program(
		target = 'saucats-docking-2d',
		source = context.path.ant_glob('docking-2d/*.cpp'),
		lib    = ['m'],
		use    = ['saucats', 'fftw', 'png', 'eigen']
	)

	context.program(
		target = 'saucats-docking-3d',
		source = context.path.ant_glob('docking-3d/*.cpp'),
		lib    = ['m'],
		use    = ['stlparser', 'saucats', 'fftw', 'png', 'eigen']
	)

